driver:
  name: docker
  use_sudo: false
  privileged: true
transport:
  name: sftp
  ruby_path: /usr/bin/ruby
provisioner:
  name: salt_solo
  salt_install: bootstrap
  local_salt_root: ../
  log_level: debug
  require_chef: false
  state_top_from_file: true
  salt_bootstrap_options: -X -p git
  salt_env: base
  salt_copy_filter:
    - .git
platforms:
  - name: centos
    driver_config:
      run_command: /usr/lib/systemd/systemd
suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -p git stable 2017.7
    state_top:
      all:
        "*":
          - josh

  - name: carbon
    provisioner:
      salt_bootstrap_options: -X -p git stable 2016.11
    state_top:
      all:
        "*":
          - josh

  - name: josh
    provisioner:
      salt_minion_id: josh

verifier:
  name: shell
  remote_exec: false
  command: py.test -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml tests/integration/$KITCHEN_SUITE
